### ISSUE TITLE
Style checker to use for Bolt

### ISSUE THREAD

**Issue by briansp2020** [HSA-Libraries/Bolt#85]
Does Bolt have a recommended style checker to use? I noticed that even though Bolt has coding style guideline, not all of it is used/enforced. In particular, use of tab character and indentation seem wrong and seems to be different depending who checks in the code.

The guideline states "Use only spaces, and indent 2 spaces at a time", it seems most of the code is indented with 4 spaces and uses tab characters as well as spaces.

![image](https://f.cloud.github.com/assets/3746601/962138/53b68452-04ea-11e3-9006-8f5eba2f42f4.png)

**Comment by briansp2020** [comment]
I just noticed that the two examples shown in the README.md uses different indentation. First one uses 4 spaces and the second one uses 2 spaces.

![image](https://f.cloud.github.com/assets/3746601/962163/dfdd4baa-04ea-11e3-8c6d-d671f169bd69.png)

**Comment by jayavanth** [comment]
Hi Brian,

We do have a Bolt coding style guideline and we encourage the developers to follow it because everybody loves code that is organized well. I agree that there are some inconsistencies in spacing in the current code, mainly because some of the code was written before the drafting of the guideline. We'll try our best to fix the current code and will make sure future commits will have cleaner code.

Thanks,
Jay
